cargo_road/cargo_road/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('events.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
]

cargo_road/events/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.home, name="home"),
    path('view-cargo', views.view_cargo, name = "view_cargo"),
    path('add-cargo', views.add_cargo, name = "add_cargo"),
    path('add-truck', views.add_truck,name = 'add_truck'),
    path('add-fedex-settlement', views.add_fedex_settlement,name = 'add_fedex_settlement'),
    path('add-driver', views.add_driver,name = 'add_driver'),
    path('driver-list',views.driver_list,name="view_drivers"),
    path('truck-list',views.truck_list,name="view_trucks"),
    path('detail-driver<driver_id>', views.detail_driver, name='detail_driver'),
    path('update-driver<driver_id>',views.update_driver,name='update_driver'),
    path('detail-truck<truck_id>', views.detail_truck, name='detail_truck'),
    path('update-truck<truck_id>', views.update_truck, name='update_truck'),
    path('detail-cargo<cargo_id>', views.detail_cargo, name='detail_cargo')
]

cargo_road/events/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db.models import Sum
# Class Truck with attributes
# name: CR + id.  (ie. CR1)
# plate: Liscnece plate
# Standard C Link
# Standard Insurance
class Truck (models.Model):
	name = models.CharField(max_length=8,blank=True) #No se si dejar o volver una calculated property?
	plate = models.CharField(max_length=8,blank=True)
	standard_c_link = models.DecimalField(decimal_places=2,max_digits=10,default=0,blank=True)
	standard_insurance = models.DecimalField(decimal_places=2,max_digits=10,default=0,blank=True)
	@property
	def total_miles(self):
		return Cargo.objects.filter(truck_id = self.id).aggregate(Sum('load_miles')).get('load_miles__sum', 0.00)
	def __str__(self):
		return self.name

class FedexSettlement (models.Model):
	settlement_fedex = models.PositiveIntegerField()
	settlement_date = models.DateField()
	fedex_payment_date =  models.DateField()
	applicant_cost = models.DecimalField(decimal_places=2,max_digits=6,default=0)
	personal_insurance = models.DecimalField(decimal_places=2,max_digits=7,default=0)
	adjust = models.DecimalField(decimal_places=2,max_digits=8,default=0)
	def __str__(self):
		return str(self.settlement_fedex)

class TruckFedexSettlement (models.Model):
	settlement_fedex = models.ForeignKey(FedexSettlement, on_delete = models.CASCADE) # Repasar on delete methods
	truck_id = models.ForeignKey(Truck, on_delete = models.CASCADE)
	c_link = models.DecimalField(decimal_places=2, max_digits=10, default=0) #Check if decimal places make sense
	mileage_taxes =  models.DecimalField(decimal_places=2, max_digits=10, default=0)
	fuel_taxes = models.DecimalField(decimal_places=2, max_digits=10, default=0)
	other_costs = models.DecimalField(decimal_places=2, max_digits=10, default=0)
	scrow = models.DecimalField(decimal_places=2, max_digits=10, default=0)
	def __str__(self):
		return str(self.settlement_fedex)
class DriverSettlement (models.Model):
	settlement_drivers = models.PositiveIntegerField()
	pay_date = models.DateField()
	def __str__(self):
		return str(self.settlement_drivers)

class Cargo (models.Model):
	shipment = models.PositiveBigIntegerField(unique=True)
	truck = models.ForeignKey(Truck, on_delete = models.CASCADE) #hablar con papi sobre on delete
	driver_settlement = models.ForeignKey(DriverSettlement, on_delete = models.CASCADE,  blank = True, null=True)
	fedex_settlement = models.ForeignKey(FedexSettlement,   on_delete = models.CASCADE, blank = True, null=True)
	description = models.CharField( max_length = 300) #Change max length
	pickup_date = models.DateField()
	delivery_date = models.DateField()
	load_miles = models.PositiveSmallIntegerField(blank = True)
	loaded_income = models.DecimalField( decimal_places = 2, max_digits = 10)
	fuel_surcharge = models.DecimalField( decimal_places = 2, max_digits = 10, default = 0)
	tolls_surcharge = models.DecimalField( decimal_places = 2, max_digits = 10, default = 0)
	dhpu = models.DecimalField( decimal_places = 2, max_digits = 10, default = 0)
	empty_income = models.DecimalField( decimal_places = 2, max_digits = 10, default = 0)
	t_check_advance = models.DecimalField( decimal_places = 2, max_digits = 10, default = 0)
	traded_value = models.DecimalField( decimal_places = 2, max_digits = 10, default = 0)
	detention = models.DecimalField( decimal_places = 2, max_digits = 10, default = 0)
	state = models.CharField( max_length = 20)

class Driver (models.Model):
	nickname = models.CharField(max_length=20, blank=True)
	name = models.CharField(max_length=30, blank=True)
	last_name = models.CharField(max_length=30, blank=True)
	w2 = models.BooleanField()
	driver_id_fedex = models.PositiveIntegerField(blank=True)
	standard_pay = models.PositiveSmallIntegerField(blank=True)
	def __str__(self):
		return self.name + " " + self.last_name + " | " + self.nickname

class DriverXCargo(models.Model):
	driver_cargo = models.ForeignKey(Cargo, on_delete = models.CASCADE)
	dri = models.ForeignKey(Driver, on_delete = models.CASCADE)
	percentage = models.PositiveSmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])

cargo_road/events/forms.py
from logging import PlaceHolder
from django import forms
from django.forms import ModelForm
from .models import Cargo, Driver, DriverXCargo, Truck, FedexSettlement
from django.utils.translation import gettext as _

class TruckForm(ModelForm):
	class Meta:
		model = Truck
		fields = ('name', 'plate', 'standard_c_link', 'standard_insurance')
		labels = {
			"name": _("Name"),
			"plate": _("Liscence Plate"),
			"standard_c_link": "Standard C Link",
			"standard_insurance": "Standard Insurance"
		}
		widgets = {
			"name": forms.TextInput(attrs={'class':'form-control','required': 'True'}),
			"plate": forms.TextInput(attrs={'class':'form-control','required': 'True'}),
			"standard_c_link": forms.NumberInput(attrs={'class':'form-control','required': 'True', 'placeholder':'C Link'}),
			"standard_insurance": forms.NumberInput(attrs={'class':'form-control','required': 'True', 'placeholder':'Standard Insurance'})
		}
class FedexSettlementForm(ModelForm):
	class Meta:
		model = FedexSettlement
		fields = ('settlement_fedex', "settlement_date", "fedex_payment_date", 'applicant_cost',
			'personal_insurance','adjust')
		labels = {
			'settlement_fedex': "Settlement Fedex",
			"settlement_date": "Settlement" + _("Date"),
			"fedex_payment_date": "Fedex Payment" + _("Date"),
			'applicant_cost': "Applicant Cost",
			'personal_insurance': "Personal Insurance",
			'adjust': "Adjust"
		}
		widgets = {
			'settlement_fedex': forms.NumberInput(attrs={'class':'form-control','required': 'True', 'placeholder':'Settlement Fedex'}),
			'settlement_date': forms.DateInput(attrs={'class':'form-control','required': 'True','type':'date'}),
			'fedex_payment_date': forms.DateInput(attrs={'class':'form-control','required': 'True','type':'date'}),
			'applicant_cost': forms.NumberInput(attrs={'class':'form-control','required': 'True', 'placeholder':'Applicant Cost'}),
			'personal_insurance': forms.NumberInput(attrs={'class':'form-control','required': 'True', 'placeholder':'Personal Insurance'}),
			'adjust': forms.NumberInput(attrs={'class':'form-control','required': 'True', 'placeholder':'Adjust'}),
		}
class CargoForm(ModelForm):
	class Meta:
		model = Cargo
		fields = ('shipment', 'truck','driver_settlement', 'fedex_settlement', 'description','pickup_date', 
		'delivery_date', 'load_miles', 'loaded_income', 'fuel_surcharge', 'tolls_surcharge', 'dhpu',
		'empty_income', 't_check_advance', 'traded_value', 'detention', 'state')

		labels = {
			'shipment': "Shipment",
			'truck': _("Truck"),
			'driver_settlement': "Driver Settlement",
			'fedex_settlement': "Fedex Settlement",
			'description': _("Description"),
			'pickup_date': "Pickup Date",
			'delivery_date': "Delivery Date",
			'load_miles': "Load Miles",
			'loaded_income': "Loaded Income",
			'fuel_surcharge': "Fuel Surcharge",
			'tolls_surcharge': "Tolls Surcharge",
			'dhpu': "DHPU",
			'empty_income': "Empty Income",
			't_check_advance': "T Check Advance",
			'traded_value': "Traded Value",
			'detention': "Detention",
			'state': "State",
		}
		widgets = {
			'shipment': forms.NumberInput(attrs={'class':'form-control','required': 'True' }),
			'truck': forms.Select(attrs={'class':'form-control','required': 'True', 'placeholder':'Truck'}),
			'driver_settlement':forms.Select(attrs={'class':'form-control', 'placeholder':'Truck'}),
			'fedex_settlement': forms.Select(attrs={'class':'form-control'}),
			'description': forms.TextInput(attrs={'class':'form-control'}),
			'pickup_date': forms.DateInput(attrs={'class':'form-control','required': 'True','type':'date'}),
			'delivery_date': forms.DateInput(attrs={'class':'form-control','required': 'True','type':'date'}),
			'load_miles': forms.NumberInput(attrs={'class':'form-control','required': 'True', }),
			'loaded_income': forms.NumberInput(attrs={'class':'form-control','required': 'True', }),
			'fuel_surcharge': forms.NumberInput(attrs={'class':'form-control','required': 'True', }),
			'tolls_surcharge': forms.NumberInput(attrs={'class':'form-control','required': 'True', }),
			'dhpu': forms.NumberInput(attrs={'class':'form-control','required': 'True', }),
			'empty_income': forms.NumberInput(attrs={'class':'form-control','required': 'True', }),
			't_check_advance': forms.NumberInput(attrs={'class':'form-control','required': 'True', }),
			'traded_value': forms.NumberInput(attrs={'class':'form-control','required': 'True', }),
			'detention': forms.NumberInput(attrs={'class':'form-control','required': 'True', }),
			'state': forms.TextInput(attrs={'class':'form-control','required': 'True'}),
		}
class DriverForm(ModelForm):
	class Meta:
		model = Driver
		fields = ('nickname', 'name', 'last_name', 'driver_id_fedex','standard_pay','w2')
		labels = {
			"nickname": "Nickname",
			"name": 'Name',
			"last_name": "Last Name",
			"driver_id_fedex": "Fedex Driver ID",
			"standard_pay": "Standard Pay",
			"w2":"W2"
		}
		widgets = {
			"nickname": forms.TextInput(attrs={'class':'form-control','required': 'True'}),
			"name": forms.TextInput(attrs={'class':'form-control','required': 'True'}),
			"last_name": forms.TextInput(attrs={'class':'form-control','required': 'True'}),
			"driver_id_fedex": forms.NumberInput(attrs={'class':'form-control','required': 'True'}),
			"standard_pay": forms.NumberInput(attrs={'class':'form-control','required': 'True'})
		}
class Driver1XCargoForm(ModelForm):
	class Meta:
		model = DriverXCargo
		fields = ('driver_cargo','dri','percentage')
		labels = {
			'driver_cargo': "Shipment Number",
			'dri': "Driver",
			'percentage': "Percentage"
		}
		widgets = {
			'dri':  forms.Select(attrs={'class':'form-control','required': 'True','name':'name'}),
			'percentage': forms.NumberInput(attrs={'class':'form-control', 'required': 'False'}),
		}
class Driver2XCargoForm(ModelForm):
	class Meta:
		model = DriverXCargo
		fields = ('driver_cargo','dri','percentage')
		labels = {
			'driver_cargo': "Shipment Number",
			'dri': "Driver",
			'percentage': "Percentage"
		}
		widgets = {
			'dri':  forms.Select(attrs={'class':'form-control','required': 'True','name':'name'}),
			'percentage': forms.NumberInput(attrs={'class':'form-control', 'required': 'False'}),
		}

cargo_road/events/views.py
import time
from django.shortcuts import render, redirect
from .forms import Driver2XCargoForm, DriverForm, Driver1XCargoForm, TruckForm, CargoForm, FedexSettlementForm
from .models import Cargo, Driver, DriverXCargo, Truck, FedexSettlement
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages

def home(request):
	print(Cargo.objects.first())
	print(Driver.objects.first())
	return render(request, 'home.html',{})
@login_required
def view_cargo (request):
	p = Paginator(Cargo.objects.all().order_by('id'), 25)
	page = request.GET.get('page')
	cargoList = p.get_page(page)
	return render(request, 'lists/view_cargo.html', {'cargoList':cargoList})
@login_required
def add_cargo (request):
	if request.method == 'POST':
		form = CargoForm(request.POST)
		print(form.data)
		if form.is_valid():
			cargo = form.save()
			print(cargo.id)
			form1 = Driver1XCargoForm(request.POST)
			form2 = Driver2XCargoForm(request.POST)
			form1.is_valid()
			form2.is_valid()
			try:
				dc1 = DriverXCargo(driver_cargo = cargo, dri = form1.clean()['dri'], percentage = form1.clean()['percentage']) 
				dc2 = DriverXCargo(driver_cargo = cargo, dri = form2.clean()['dri'], percentage = form2.clean()['percentage']) 
				dc1.save()
				dc2.save()
				return redirect('home')
			except:
				messages.success(request, str(form1.errors))
		else:
			messages.success(request, str(form.errors))
	form1 = Driver1XCargoForm(request.POST)
	form2 = Driver2XCargoForm(request.POST)
	form = CargoForm(request.POST)
	return render(request, 'create/add_cargo.html', {'form':form, 'form1': form1, 'form2': form2})
@login_required
def add_truck(request):
	if request.method == 'POST':
		form = TruckForm(request.POST)
		if (form.is_valid()):
			form.save()
			return redirect("home")
	form = TruckForm(request.POST)
	return render(request, 'create/add_truck.html', {'form': form})
@login_required
def add_fedex_settlement(request):
	if request.method == 'POST':
		form = FedexSettlementForm(request.POST)
		if (form.is_valid()):
			form.save()
			return redirect("home")
	else:
		form = FedexSettlementForm(request.POST)
	return render(request, 'create/fedex_settlement.html', {'form': form})
@login_required
def add_driver(request):
	if request.method == 'POST':
		form = DriverForm(request.POST)
		if (form.is_valid()):
			form.save()
			return redirect("home")
	else:
		form = DriverForm(request.POST)
	return render(request, 'create/add_driver.html', {'form': form})
@login_required
def driver_list(request):
	drivers = Driver.objects.order_by('name')
	return render(request, 'lists/driver_list.html', {'drivers':drivers})
@login_required
def truck_list(request):
	trucks = Truck.objects.order_by('name')
	return render(request, 'lists/truck_list.html', {'trucks':trucks})
@login_required
def detail_driver(request, driver_id):
	driver = Driver.objects.get(pk=driver_id)
	#cargo = DriverXCargo.objects.filter(driver_id = did)
	return render(request, 'detail/driver.html', {'driver':driver})
@login_required
def detail_truck(request, truck_id):
	truck = Truck.objects.get(pk=truck_id)
	p = Paginator(Cargo.objects.filter(truck_id = truck_id).order_by('-pickup_date'),10)
	page = request.GET.get('page')
	cargo = p.get_page(page)
	
	return render(request, 'detail/view_truck.html', {'truck':truck, 'cargos':cargo})
@login_required
def update_driver(request, driver_id):
	driver = Driver.objects.get(pk=driver_id)
	form = DriverForm(request.POST or None, instance=driver)
	if request.method == 'POST':
		if (form.is_valid()):
			form.save()
			return redirect("home")
	return render(request, 'create/add_driver.html', {'form': form, 'driver':driver})
@login_required
def update_truck(request, truck_id):
	truck = Truck.objects.get(pk = truck_id)
	form = TruckForm(request.POST or None, instance=truck)
	if request.method == 'POST':
		if form.is_valid():
			form.save()
			return redirect('home')
	return render (request,'create/add_truck.html',{'form':form})
@login_required
def detail_cargo(request, cargo_id):
	cargo = Cargo.objects.get(pk = cargo_id)
	return render(request, 'detail/cargo.html', {'cargo':cargo})

cargo_road/events/templates/create/add_cargo.html
{% extends 'base.html' %}

{% block content %}
<h1>Add Cargo</h1>
</br>
<form class="row g-3" action = "" method = POST >
    {%csrf_token%}
    <div class="col-md-11">
      <label for="inputEmail4" class="form-label">Shipment Number</label>
      {{form.shipment}}
    </div>
    <div class="col-md-1">
        <label for="inputEmail4" class="form-label">State</label>
        {{form.state}}
      </div>
    <div class="col-md-6">
        <label for="inputPassword4" class="form-label">Pickup Date</label>
        {{form.pickup_date}}
      </div>
      <div class="col-md-6">
        <label for="inputPassword4" class="form-label">Delivery Date</label>
        {{form.delivery_date}}
      </div>
    <div class="col-md-4">
      <label for="inputPassword4" class="form-label">Truck Name</label>
      {{form.truck}}
    </div>
    <div class="col-md-4">
        <label for="inputPassword4" class="form-label">Driver Settlement</label>
        {{form.driver_settlement}}
      </div>
      <div class="col-md-4">
        <label for="inputPassword4" class="form-label">Fedex Settlement</label>
        {{form.fedex_settlement}}
      </div>
      <div class="col-md-6">
        <label for="inputPassword4" class="form-label">Driver 1</label>
        {{form1.dri}}
      </div>
      <div class="col-md-6">
        <label for="inputPassword4" class="form-label">Percentage Driver 1</label>
        {{form1.percentage}}
      </div>
      <div class="col-md-6" name="dr2">
        <label for="inputPassword4" class="form-label">Driver 2</label>
        {{form2.dri}}
      </div>
      <div class="col-md-6">
        <label for="inputPassword4" class="form-label">Percentage Driver 2</label>
        {{form2.percentage}}
      </div>
      <div class="col-md-6">
        <label for="inputPassword4" class="form-label">Loaded Income</label>
        {{form.loaded_income}}
      </div>  
      <div class="col-md-6">
        <label for="inputPassword4" class="form-label">Load Miles</label>
        {{form.load_miles}}
      </div>
      <div class="col-md-4">
        <label for="inputPassword4" class="form-label">Fuel Surcharge</label>
        {{form.fuel_surcharge}}
      </div>
      <div class="col-md-4">
        <label for="inputPassword4" class="form-label">Tolls Surcharge</label>
        {{form.tolls_surcharge}}
      </div>
      <div class="col-md-4">
        <label for="inputPassword4" class="form-label">DHPU</label>
        {{form.dhpu}}
      </div>
      <div class="col-md-3">
        <label for="inputPassword4" class="form-label">Empty Income</label>
        {{form.empty_income}}
      </div>
      <div class="col-md-3">
        <label for="inputPassword4" class="form-label">T Check Advance</label>
        {{form.t_check_advance}}
      </div>
      <div class="col-md-3">
        <label for="inputPassword4" class="form-label">Traded Value</label>
        {{form.traded_value}}
      </div>
      <div class="col-md-3">
        <label for="inputPassword4" class="form-label">Detention</label>
        {{form.detention}}
      </div>
      <div class="col-md-12">
        <label for="inputPassword4" class="form-label">Description</label>
        {{form.description}}
      </div>
      <div class="col-md-4">
        <input type ="submit" value = "Submit" class="btn btn-success"></input>
        
      </div>
</form>
<!-- <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_driver").change(function () {
      var url = $("#cargoForm").attr("data-driver-url");  // get the url of the `load_cities` view
      var driverId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'driver': driverId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_percentage").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script> -->
</br>
</br>

{% endblock %}

cargo_road/events/templates/create/add_driver.html
{% extends 'base.html' %}

{% block content %}
<h1>Add Driver</h1>
</br>
<form class="row g-3" action = "" method =POST>
    {%csrf_token%}
    <div class="col-md-6">
      <label for="inputEmail4" class="form-label">Name</label>
      {{form.name}}
    </div>
    <div class="col-md-6">
      <label for="inputPassword4" class="form-label">Last Name</label>
      {{form.last_name}}
    </div>
    <div class="col-12">
      <label for="inputAddress" class="form-label">Nickname</label>
      {{form.nickname}}
    </div>
    <div class="col-6">
      <label for="inputAddress2" class="form-label">Fedex Driver ID</label>
      {{form.driver_id_fedex}}
    </div>
    <div class="col-md-6">
      <label for="inputCity" class="form-label">Standard Pay</label>
      {{form.standard_pay}}
    </div>
    <div class="col-12">
      <div class="form-check">
        {{form.w2}}
        <label class="form-check-label" for="gridCheck">
          W2
        </label>
      </div>
    </div>
    <div class="col-12">
        <input type ="submit" value = "Submit" class="btn btn-success"></input>
    </div>
  </form>
{% endblock %}

cargo_road/events/templates/create/add_truck.html
{%extends 'base.html'%}
{%block content%}
<h1>Add Truck</h1>
</br>
<form class="row g-3" action = "" method =POST>
    {%csrf_token%}
    <div class="col-md-6">
      <label for="inputEmail4" class="form-label">Nombre</label>
      {{form.name}}
    </div>
    <div class="col-md-3">
        <label for="inputState" class="form-label">Standard C Link</label>
        {{form.standard_c_link}}
      </div>
      <div class="col-md-3">
        <label for="inputState" class="form-label">Standard Insurance</label>
        {{form.standard_insurance}}
      </div>
    <div class="col-md-12">
      <label for="inputCity" class="form-label">Placa</label>
      {{form.plate}}
    </div>
</br>
    <div class="col-12">
        <center>
            <input type ="submit" value = "Submit" class="btn btn-success"></input>
        </center>

    </div>
  </form>
</br>
</br>
{% endblock %}

cargo_road/events/templates/create/fedex_settlement.html
{% extends 'base.html' %}

{% block content %}
<h1>Fedex Settlement</h1>
</br>
<form action = "" method =POST>
    {%csrf_token%}
    {{form.as_p}}
    <input type ="submit" value = "Submit" class="btn btn-success"></input>
</form>

</br>
</br>
{% endblock %}